CREATE TABLE order_address
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country VARCHAR(256) NOT NULL,
    city    VARCHAR(256) NOT NULL,
    address TEXT         NOT NULL
);

CREATE TABLE card_info
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    card_number      VARCHAR(128) NOT NULL,
    name_on_the_card VARCHAR(256) NOT NULL,
    validity_period  VARCHAR(64)  NOT NULL,
    cvv              VARCHAR(32)  NOT NULL
);

CREATE TABLE buyer_info
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(256) NOT NULL,
    surname VARCHAR(256) NOT NULL,
    phone   VARCHAR(64)  NOT NULL
);

CREATE TABLE tea_order
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address_id    BIGINT REFERENCES order_address (id),
    buyer_info_id BIGINT REFERENCES buyer_info (id),
    card_info_id  BIGINT REFERENCES card_info (id),
    user_id       BIGINT       REFERENCES tea_user (id) ON DELETE SET NULL,
    status        VARCHAR(256) NOT NULL,
    created_at    TIMESTAMP,
    delivery_at   TIMESTAMP,
    total_sum     FLOAT
);

CREATE TABLE product_in_order
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    product_id BIGINT REFERENCES product (id) ON DELETE CASCADE ,
    amount     INT CHECK ( amount > 0 ),
    order_id   BIGINT REFERENCES tea_order(id) ON DELETE CASCADE
);

CREATE TABLE chat_room(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE user_room(
    user_id BIGINT REFERENCES tea_user(id) ON DELETE CASCADE,
    room_id BIGINT REFERENCES chat_room(id) ON DELETE CASCADE,
    PRIMARY KEY(user_id, room_id)
);

CREATE TABLE chat_message(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT,
    created_at TIMESTAMP,
    message_type VARCHAR,
    is_reading BOOLEAN,
    by_user_id BIGINT REFERENCES tea_user(id) ON DELETE CASCADE,
    chat_id BIGINT REFERENCES chat_room(id) ON DELETE CASCADE
);